#!/bin/bash

# =============================================================================
# NS-3 3.45 Installation Script for ns3_gazebo
# =============================================================================

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
NS3_VERSION="3.45"
NS3_DIR="ns-allinone-${NS3_VERSION}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_dependencies() {
    log_info "Checking system dependencies..."

    # Required packages
    REQUIRED_PACKAGES=(
        "build-essential"
        "cmake"
        "python3"
        "python3-dev"
        "pkg-config"
        "sqlite3"
        "libsqlite3-dev"
        "libxml2-dev"
        "libgtk-3-dev"
        "qtbase5-dev"
        "qtchooser"
        "qt5-qmake"
        "qtbase5-dev-tools"
        "gir1.2-goocanvas-2.0"
        "python3-gi"
        "python3-gi-cairo"
        "python3-pygraphviz"
        "gir1.2-gtk-3.0"
        "ipython3"
        "openmpi-bin"
        "openmpi-common"
        "openmpi-doc"
        "libopenmpi-dev"
        "mercurial"
        "unzip"
        "gdb"
        "valgrind"
    )

    # Check if packages are installed
    for package in "${REQUIRED_PACKAGES[@]}"; do
        if ! dpkg -l | grep -q "^ii  $package "; then
            log_warning "Missing package: $package"
            MISSING_PACKAGES+=("$package")
        fi
    done

    if [ ${#MISSING_PACKAGES[@]} -ne 0 ]; then
        log_info "Installing missing packages..."
        sudo apt update
        sudo apt install -y "${MISSING_PACKAGES[@]}"
    fi

    log_success "All dependencies satisfied"
}

download_ns3() {
    log_info "Downloading NS-3 ${NS3_VERSION}..."

    cd "$PROJECT_DIR"

    # Check if already exists
    if [ -d "$NS3_DIR" ]; then
        log_warning "NS-3 directory already exists. Remove it to reinstall."
        read -p "Remove existing NS-3 installation? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf "$NS3_DIR"
        else
            log_info "Using existing NS-3 installation"
            return
        fi
    fi

    # Download NS-3
    NS3_URL="https://www.nsnam.org/releases/ns-allinone-${NS3_VERSION}.tar.bz2"
    wget -O "ns-allinone-${NS3_VERSION}.tar.bz2" "$NS3_URL"

    # Extract
    tar -xjf "ns-allinone-${NS3_VERSION}.tar.bz2"
    rm "ns-allinone-${NS3_VERSION}.tar.bz2"

    log_success "NS-3 ${NS3_VERSION} downloaded and extracted"
}

build_ns3() {
    log_info "Building NS-3 ${NS3_VERSION}..."

    cd "$PROJECT_DIR/$NS3_DIR"

    # Build NS-3 (optimized build)
    ./build.py --enable-examples --enable-tests

    # Configure NS-3 with required modules
    cd "ns-3.${NS3_VERSION}"
    ./ns3 configure --build-profile=default --enable-examples --enable-tests
    ./ns3 build

    log_success "NS-3 ${NS3_VERSION} built successfully"
}

verify_installation() {
    log_info "Verifying NS-3 installation..."

    NS3_BUILD_DIR="$PROJECT_DIR/$NS3_DIR/ns-3.${NS3_VERSION}/build"

    # Check if key libraries exist
    REQUIRED_LIBS=(
        "libns3.${NS3_VERSION}-core-default.so"
        "libns3.${NS3_VERSION}-network-default.so"
        "libns3.${NS3_VERSION}-wifi-default.so"
        "libns3.${NS3_VERSION}-internet-default.so"
        "libns3.${NS3_VERSION}-mobility-default.so"
        "libns3.${NS3_VERSION}-tap-bridge-default.so"
    )

    for lib in "${REQUIRED_LIBS[@]}"; do
        if [ ! -f "$NS3_BUILD_DIR/lib/$lib" ]; then
            log_error "Required library not found: $lib"
            exit 1
        fi
    done

    # Test NS-3 installation
    cd "$PROJECT_DIR/$NS3_DIR/ns-3.${NS3_VERSION}"
    if ./ns3 run hello-simulator > /dev/null 2>&1; then
        log_success "NS-3 installation verified successfully"
    else
        log_error "NS-3 verification failed"
        exit 1
    fi
}

create_environment_file() {
    log_info "Creating NS-3 environment configuration..."

    ENV_FILE="$PROJECT_DIR/scripts/ns3_env.sh"
    cat > "$ENV_FILE" << EOF
#!/bin/bash
# NS-3 Environment Configuration
# Generated by install_ns3.sh

export NS3_VERSION="${NS3_VERSION}"
export NS3_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)/${NS3_DIR}"
export NS3_BUILD_DIR="\$NS3_DIR/ns-3.\${NS3_VERSION}/build"
export NS3_LIB_DIR="\$NS3_BUILD_DIR/lib"
export NS3_INCLUDE_DIR="\$NS3_BUILD_DIR/include"

# Add NS-3 to library path
export LD_LIBRARY_PATH="\$NS3_LIB_DIR:\$LD_LIBRARY_PATH"

# Function to source this file
source_ns3_env() {
    echo "NS-3 environment loaded:"
    echo "  Version: \$NS3_VERSION"
    echo "  Directory: \$NS3_DIR"
    echo "  Libraries: \$NS3_LIB_DIR"
}

# Auto-display when sourced
if [ "\${BASH_SOURCE[0]}" != "\${0}" ]; then
    source_ns3_env
fi
EOF

    chmod +x "$ENV_FILE"
    log_success "Environment file created: $ENV_FILE"
}

main() {
    log_info "Starting NS-3 ${NS3_VERSION} installation for ns3_gazebo..."

    # Check system requirements
    if ! command -v wget &> /dev/null; then
        log_error "wget is required but not installed"
        exit 1
    fi

    # Run installation steps
    check_dependencies
    download_ns3
    build_ns3
    verify_installation
    create_environment_file

    log_success "NS-3 ${NS3_VERSION} installation completed successfully!"
    log_info "To use NS-3 environment: source scripts/ns3_env.sh"
}

# Script entry point
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi